update: only run test when edited Makefile/sh/bats

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -45,12 +45,19 @@ EOF
 	exit 1
 fi
 
-# make test/build check
-test_result=$(make test)
-test_status=$?
-if [ $test_status -ne 0 ]; then
-    echo "git pre-commit error: test has failed." >&2
-    exit 1
+# make-test check
+git status --porcelain \
+    | grep -e '^[AM].*' \
+    | awk '{ print $2 }' \
+    | grep -iq -e 'Makefile' -e '.*\.sh' -e '.*\.bats'
+if [ $? -eq 0 ]; then
+    echo "start: make test ..."
+    test_result=$(make test)
+    test_status=$?
+    if [ $test_status -ne 0 ]; then
+        echo "git pre-commit error: test has failed." >&2
+        exit 1
+    fi
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
